# Generated by Django 4.0.6 on 2022-09-11 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0003_alter_customer_phone_number_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
