# Generated by Django 4.0.6 on 2022-07-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_customer_stock_worker_delete_greeting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Staff',
        ),
    ]
