# Generated by Django 4.0.6 on 2022-07-26 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_staff_phone_number_alter_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
