# Generated by Django 4.0.6 on 2022-08-05 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_stock_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hello.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sales',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hello.stock'),
        ),
    ]
